runtime: python311

env_variables:
  FLASK_ENV: production
  DATABASE_PATH: "/tmp/school.db"
  SECRET_KEY: "your-production-secret-key-change-this"

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
