runtime: python311

env_variables:
  FLASK_ENV: production
  DATABASE_PATH: "/tmp/school.db"
  SECRET_KEY: "your-production-secret-key-change-this"
  
  # Google Analytics Configuration
  # Get your GA4 Measurement ID from https://analytics.google.com
  # Format: G-XXXXXXXXXX
  GOOGLE_ANALYTICS_ID: "G-XJ97NGS36D"

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
